version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - mysql
    networks:
      - neko-network

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    networks:
      - neko-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=${API_URL}
    depends_on:
      - api
    networks:
      - neko-network

networks:
  neko-network:
    driver: bridge
