CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    nickname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    api_key VARCHAR(255) NOT NULL DEFAULT '',
    blacklisted BOOLEAN DEFAULT FALSE,
    gold BOOLEAN DEFAULT FALSE
);
